import type { Person } from "@/types/shared";

export const mockPeople: Person[] = [
  {
    id: "1",
    name: "James Wilson",
    age: 25,
    gender: "Men",
    location: "Toronto, Canada",
    title: "CEO",
    generation: "Gen Z",
    industry: "Fintech",
    feedback: "When he got his first job he didn't know what to do... all they told him was \"here are some boxes figure out what to do with them\" lol but from there he kept going until he created his own business. Gotta keep going to keep growing and if you're not stacking you're lackin'",
    reaction: "intrigued",
    fullReaction: "James Wilson, a Gen Z fintech CEO with a high risk tolerance and interest in innovation, is likely to be intrigued by an idea that targets his generation with a fintech app.",
    position: { x: 0.3, y: 0.4, z: 0.6 },
  },
  {
    id: "2",
    name: "Sarah Chen",
    age: 32,
    gender: "Women",
    location: "Clovis, CA",
    title: "Software Engineer",
    generation: "Millennial",
    industry: "Software Development",
    feedback: "In the beginning, where he was just going to work for a little while to save up so he could travel and stayed 50 plus years. Amazing how someone can be inspired to stay with a company for so long.",
    reaction: "inspired",
    fullReaction: "Sarah Chen, a millennial software engineer who values financial planning and career growth, is likely to be inspired by an app that helps her demographic manage finances effectively.",
    position: { x: -0.2, y: 0.7, z: -0.3 },
  },
  {
    id: "3",
    name: "Marcus Thompson",
    age: 28,
    gender: "Men",
    location: "Montreal, Quebec",
    title: "Product Manager",
    generation: "Gen Z",
    industry: "Technology",
    feedback: "The most important thing is building something that people actually want to use. You can have the best technology in the world but if it doesn't solve a real problem, nobody cares.",
    reaction: "interested",
    fullReaction: "Marcus Thompson, a Gen Z product manager in tech, is likely to be interested in evaluating the product-market fit and user experience of a new fintech solution.",
    position: { x: 0.8, y: -0.2, z: 0.1 },
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    age: 29,
    gender: "Women",
    location: "Vancouver, BC",
    title: "Marketing Director",
    generation: "Gen Z",
    industry: "Marketing",
    feedback: "Gen X in Canada is such an underserved market. Most apps focus on millennials or boomers, but Gen X has real money and specific needs that nobody talks about.",
    reaction: "excited",
    fullReaction: "Emily Rodriguez, a Gen Z marketing director, is likely to be excited about the market opportunity and positioning strategy of targeting Gen X Canadians.",
    position: { x: -0.5, y: 0.3, z: 0.8 },
  },
  {
    id: "5",
    name: "David Kim",
    age: 35,
    gender: "Men",
    location: "Calgary, Alberta",
    title: "Financial Advisor",
    generation: "Millennial",
    industry: "Financial Services",
    feedback: "Canadian financial regulations are complex, and Gen X clients often feel overwhelmed by existing solutions. A simple, compliant app could really help bridge that gap.",
    reaction: "analytical",
    fullReaction: "David Kim, a millennial financial advisor, is likely to take an analytical approach to evaluating the compliance and practical utility of the proposed fintech solution.",
    position: { x: 0.1, y: -0.6, z: -0.4 },
  },
  {
    id: "6",
    name: "Lisa Wang",
    age: 31,
    gender: "Women",
    location: "Ottawa, Ontario",
    title: "UX Designer",
    generation: "Millennial",
    industry: "Design",
    feedback: "The key is making sure the interface doesn't alienate Gen X users who might not be as tech-savvy as younger generations. Clean, simple design with clear value props.",
    reaction: "thoughtful",
    fullReaction: "Lisa Wang, a millennial UX designer, is likely to be thoughtful about the user experience considerations and design challenges for serving Gen X users.",
    position: { x: -0.7, y: -0.1, z: 0.5 },
  },
  {
    id: "7",
    name: "Ryan O'Connor",
    age: 26,
    gender: "Men",
    location: "Halifax, Nova Scotia",
    title: "Business Analyst",
    generation: "Gen Z",
    industry: "Finance",
    feedback: "Atlantic Canada has different economic pressures than Toronto or Vancouver. Regional considerations could be a major differentiator for this type of product.",
    reaction: "strategic",
    fullReaction: "Ryan O'Connor, a Gen Z business analyst in finance, is likely to think strategically about regional market differences and competitive positioning.",
    position: { x: 0.6, y: 0.5, z: -0.7 },
  },
  {
    id: "8",
    name: "Jessica Brown",
    age: 33,
    gender: "Women",
    location: "Winnipeg, Manitoba",
    title: "Operations Manager",
    generation: "Millennial",
    industry: "Operations",
    feedback: "Execution is everything. Lots of fintech startups have good ideas but fail on the operational side. Customer support, onboarding, compliance - that's where you win or lose.",
    reaction: "practical",
    fullReaction: "Jessica Brown, a millennial operations manager, is likely to focus on the practical execution challenges and operational requirements for launching a successful fintech product.",
    position: { x: -0.3, y: 0.8, z: 0.2 },
  },
];
